--Constants
WIDTH = 800
HEIGHT = 600
UNIT = 80 --pixels, same for horizontal and vertical
ORIGIN_X = WIDTH / 2
ORIGIN_Y = HEIGHT - UNIT
DEBUG_ORIGIN_X = ORIGIN_X + 3*UNIT

TRANSITION = UNIT / 4
PADDING = UNIT / 10
EFFECTS_HANDLE_HEIGHT = UNIT / 3


